import type { Metadata } from 'next';
import './globals.css';
import { fontVariables } from './fonts';
import { SmoothScroll } from '@/components/SmoothScroll/SmoothScroll';
import { ShopButton } from '@/components/ShopButton/ShopButton';
import { CookieBanner } from '@/components/CookieBanner/CookieBanner';
import { PageTransition } from '@/components/PageTransition/PageTransition';
import { SoundLayer } from '@/components/Sound/SoundLayer';

export const metadata: Metadata = {
  metadataBase: new URL('https://gazeholdings.com'),
  title: { default: 'Gaze Holdings — A House of Brands', template: '%s · Gaze Holdings' },
  description: 'The institutional home of Gaze Holdings Limited — a Nairobi-rooted House of Brands: Gaze Furnishings, the Gaze Leadership Institute, Her Gaze Global and Gaze Press Global.',
  openGraph: {
    type: 'website',
    siteName: 'Gaze Holdings',
    title: 'Gaze Holdings — A House of Brands',
    description: 'Four houses. One standard. Built for legacy.',
    // OG image is dynamically generated by app/opengraph-image.tsx
  },
  twitter: { card: 'summary_large_image' },
  robots: { index: true, follow: true },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={fontVariables} suppressHydrationWarning>
      <head>
        {/* `?motion=full` forces full motion for this session even when the OS asks for reduced motion
            (for design reviews); `?motion=auto` goes back to following the OS. Runs before first paint. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `try{var m=new URLSearchParams(location.search).get('motion');if(m)sessionStorage.setItem('gaze.motion',m);if(sessionStorage.getItem('gaze.motion')==='full')document.documentElement.dataset.motion='full'}catch(e){}`,
          }}
        />
      </head>
      <body className="bg-obsidian text-ivory">
        <SmoothScroll>
          {children}
          <ShopButton />
          <CookieBanner />
        </SmoothScroll>
        <PageTransition />
        <SoundLayer />
      </body>
    </html>
  );
}
