import type { Metadata } from 'next';
import { Outfit, Cormorant_Garamond, Inter } from 'next/font/google';
import './globals.css';
import { SmoothScroll } from '@/components/SmoothScroll/SmoothScroll';
import { Cursor } from '@/components/Cursor/Cursor';
import { ShopButton } from '@/components/ShopButton/ShopButton';
import { CookieBanner } from '@/components/CookieBanner/CookieBanner';

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600'],
  variable: '--font-outfit',
  display: 'swap',
});

const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300', '400'],
  style: ['italic', 'normal'],
  variable: '--font-cormorant',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  metadataBase: new URL('https://gazeholdings.com'),
  title: { default: 'Gaze Holdings — A group of brands built for legacy', template: '%s · Gaze Holdings' },
  description: 'The institutional home of Gaze Holdings Limited — a Kenya-rooted, globally-scaled House of Brands spanning interiors, publishing, leadership, broadcast, and women\'s transformation.',
  openGraph: {
    type: 'website',
    siteName: 'Gaze Holdings',
    title: 'Gaze Holdings — A group of brands built for legacy',
    description: 'Five divisions. One signature. Built for legacy.',
    // OG image is dynamically generated by app/opengraph-image.tsx
  },
  twitter: { card: 'summary_large_image' },
  robots: { index: true, follow: true },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${outfit.variable} ${cormorant.variable} ${inter.variable}`}>
      <body className="bg-obsidian text-ivory">
        <SmoothScroll>
          <Cursor />
          {children}
          <ShopButton />
          <CookieBanner />
        </SmoothScroll>
      </body>
    </html>
  );
}
